// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
)

type Cheese struct {
	ID            int64
	Departement   sql.NullString
	Fromage       sql.NullString
	Pagefrancaise sql.NullString
	Englishpage   sql.NullString
	Lait          sql.NullString
	Geoshape      sql.NullString
	Geopoint2d    sql.NullString
}
