// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

type Cheese struct {
	ID            int64
	Departement   string
	Fromage       string
	Pagefrancaise string
	Englishpage   string
	Lait          string
	Geoshape      string
	Geopoint2d    string
}
